# Generated by Django 4.2.7 on 2023-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_comment_listing_remove_comments_auction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlisted_by", to="auctions.listing"
            ),
        ),
    ]
